#!/usr/bin/env python3
"""Single-source documentation generator for Torio.

Prose lives once, under ``docs/content/``:

  * ``blocks/``   — shareable sections, each addressed by its filename stem;
  * ``pages/``    — site page sources, rendered to ``site/*.html``;
  * ``runbooks/`` — runbook sources, rendered to ``docs/runbooks/*.md``.

A page or runbook pulls a block in with ``<!-- include: block-id -->``. Because
both outputs expand the *same* block file, a section shared by the getting
started page and the reference page cannot drift: there is only one copy.

Standard library only, matching the other scripts here. Two modes:

    python3 scripts/build_docs.py            # write the generated outputs
    python3 scripts/build_docs.py --check    # render in memory, diff, never write

``--check`` performs no writes and no network access, so it is safe to run as a
validation gate.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "docs" / "content"
LAYOUT = CONTENT / "_layout.html"

# Where this project lives. Every generated page links back to it, so the slug
# is written once here rather than once per page: moving the repository to an
# organisation is then one edit plus ``make docs``.
#
# Deliberately not overridable by the environment, unlike ``TORIO_REPO`` in
# scripts/install.sh. That installer resolves assets at run time on someone
# else's machine; this generator writes files that are committed and diffed by
# ``--check``. An environment-dependent output would make the drift gate report
# a different answer per machine, which is worse than a constant to edit.
REPO_SLUG = "wzslr321/torio"
REPO_URL = f"https://github.com/{REPO_SLUG}"

BANNER_HTML = (
    "<!-- Generated by scripts/build_docs.py from {source} — do not edit.\n"
    "     Edit the source and re-run: python3 scripts/build_docs.py -->"
)
BANNER_MD = (
    "<!-- Generated by scripts/build_docs.py from {source} — do not edit.\n"
    "     Edit the source and re-run: python3 scripts/build_docs.py -->"
)

INCLUDE = re.compile(
    r"^[ \t]*<!--[ \t]*include:[ \t]*([A-Za-z0-9_-]+)"
    r"(?:[ \t]+level=(\d))?"
    r'(?:[ \t]+heading="([^"]*)")?'
    r"[ \t]*-->[ \t]*$",
    re.MULTILINE,
)
FRONT_MATTER = re.compile(r"\A---[ \t]*\n(.*?)\n---[ \t]*\n", re.DOTALL)
HEADING = re.compile(r"^(#{1,6})[ \t]+(.*?)[ \t]*(?:\{#([A-Za-z0-9_-]+)\})?[ \t]*$")
FENCE = re.compile(r"^```[ \t]*([A-Za-z0-9_+-]*)[ \t]*$")
TABLE_SEP = re.compile(r"^\|[ \t:|-]+\|$")
TOC = re.compile(r"^[ \t]*<!--[ \t]*toc[ \t]*-->[ \t]*$", re.MULTILINE)
OL_ITEM = re.compile(r"^(\d+)\.[ \t]+(.*)$")
UL_ITEM = re.compile(r"^[-*][ \t]+(.*)$")

MAX_INCLUDE_DEPTH = 16


class BuildError(Exception):
    """A source problem that must stop the build rather than be papered over."""


@dataclass
class Block:
    id: str
    meta: dict[str, str]
    body: str


@dataclass
class Page:
    source: Path
    meta: dict[str, str]
    body: str
    outputs: list[str] = field(default_factory=list)


# --------------------------------------------------------------------------
# sources
# --------------------------------------------------------------------------


def parse_source(text: str, where: str) -> tuple[dict[str, str], str]:
    """Split optional ``---`` front matter from the body.

    Front matter is a flat ``key: value`` mapping; nothing here needs nesting,
    and refusing to invent a YAML subset keeps the format unambiguous.
    """
    match = FRONT_MATTER.match(text)
    if not match:
        return {}, text

    meta: dict[str, str] = {}
    for lineno, line in enumerate(match.group(1).splitlines(), start=2):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise BuildError(f"{where}:{lineno}: front matter line is not 'key: value': {line!r}")
        value = value.strip()
        # Quoting is how a value carries a colon of its own.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value
    return meta, text[match.end() :]


def load_blocks() -> dict[str, Block]:
    blocks: dict[str, Block] = {}
    block_dir = CONTENT / "blocks"
    if not block_dir.is_dir():
        raise BuildError(f"no block directory at {block_dir.relative_to(ROOT)}")
    for path in sorted(block_dir.glob("*.md")):
        meta, body = parse_source(path.read_text(encoding="utf-8"), where=str(path.relative_to(ROOT)))
        blocks[path.stem] = Block(id=path.stem, meta=meta, body=body)
    if not blocks:
        raise BuildError(f"no blocks found in {block_dir.relative_to(ROOT)}")
    return blocks


def shift_headings(text: str, top_level: int) -> str:
    """Re-level a block so its shallowest heading sits at ``top_level``.

    A block is written once but appears at different depths — a step inside the
    getting started page, a top-level section in the reference. Shifting on
    include lets one source serve both. Fenced code is skipped so a shell
    comment is never mistaken for a heading.
    """
    lines = text.split("\n")
    in_fence = False
    levels: list[int] = []
    for line in lines:
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        heading = HEADING.match(line.strip())
        if heading:
            levels.append(len(heading.group(1)))
    if not levels:
        return text

    delta = top_level - min(levels)
    if delta == 0:
        return text

    out: list[str] = []
    in_fence = False
    for line in lines:
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            out.append(line)
            continue
        heading = HEADING.match(line.strip()) if not in_fence else None
        if heading:
            level = max(1, min(6, len(heading.group(1)) + delta))
            out.append("#" * level + line.strip()[len(heading.group(1)) :])
        else:
            out.append(line)
    return "\n".join(out)


def expand_toc(text: str) -> str:
    """Replace a ``<!-- toc -->`` marker with a list of the document's steps.

    Generated rather than hand-written so a long single page can be scanned
    without the contents list becoming another thing that drifts.
    """
    if not TOC.search(text):
        return text

    entries: list[str] = []
    in_fence = False
    for line in text.split("\n"):
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        heading = HEADING.match(line.strip())
        if heading and len(heading.group(1)) == 3:
            title = heading.group(2)
            anchor = heading.group(3) or slug(title)
            entries.append(f"- [{title}](#{anchor})")
    return TOC.sub("\n".join(entries) if entries else "", text)


def strip_anchor_syntax(text: str) -> str:
    """Drop ``{#anchor}`` heading suffixes, which only mean something in HTML."""
    lines = text.split("\n")
    in_fence = False
    out: list[str] = []
    for line in lines:
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            out.append(line)
            continue
        heading = HEADING.match(line.strip()) if not in_fence else None
        if heading and heading.group(3):
            out.append(f"{heading.group(1)} {heading.group(2)}")
        else:
            out.append(line)
    return "\n".join(out)


def check_block_portability(blocks: dict[str, Block]) -> list[str]:
    """Reject links that cannot survive both output formats.

    A block is rendered into site HTML *and* into runbook Markdown. A
    ``page.html`` link resolves on the site but dangles from a runbook, so
    cross-page links belong in the including page's own prose, not in a shared
    block. Fragment-only and absolute links travel fine.
    """
    problems: list[str] = []
    for block_id in sorted(blocks):
        for target in re.findall(r"\[[^\]]*\]\(([^)]+)\)", blocks[block_id].body):
            if target.split("#", 1)[0].endswith(".html"):
                problems.append(
                    f"blocks/{block_id}.md: shared blocks cannot link to {target!r} — "
                    "site-relative links dangle in the generated runbooks; "
                    "move the cross-reference into the including page"
                )
    return problems


def retitle_first_heading(text: str, title: str) -> str:
    """Rename a block's own top heading, keeping its level and anchor.

    Lets a numbered step ("Step 1 — Build the CLI") reuse a block that calls
    itself something else elsewhere, without the page having to add a second
    heading above the included one.
    """
    lines = text.split("\n")
    for index, line in enumerate(lines):
        heading = HEADING.match(line.strip())
        if not heading:
            continue
        anchor = f" {{#{heading.group(3)}}}" if heading.group(3) else ""
        lines[index] = f"{heading.group(1)} {title}{anchor}"
        break
    return "\n".join(lines)


def expand_includes(text: str, blocks: dict[str, Block], where: str, depth: int = 0) -> str:
    """Expand ``<!-- include: id [level=N] [heading="…"] -->`` markers."""
    if depth > MAX_INCLUDE_DEPTH:
        raise BuildError(f"{where}: include nesting exceeded {MAX_INCLUDE_DEPTH} levels (cycle?)")

    def replace(match: re.Match[str]) -> str:
        block_id, level, heading = match.group(1), match.group(2), match.group(3)
        block = blocks.get(block_id)
        if block is None:
            known = ", ".join(sorted(blocks)) or "none"
            raise BuildError(f"{where}: unknown block {block_id!r} (known: {known})")
        body = block.body.strip("\n")
        if level:
            body = shift_headings(body, int(level))
        if heading:
            body = retitle_first_heading(body, heading)
        return expand_includes(body, blocks, where=f"{where} -> {block_id}", depth=depth + 1)

    return INCLUDE.sub(replace, text)


# --------------------------------------------------------------------------
# markdown subset -> HTML
# --------------------------------------------------------------------------


def slug(text: str) -> str:
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


SHELL_LANGS = {"bash", "sh", "shell", "console"}


def highlight_shell(line: str) -> str:
    """Tint one shell line: quoted strings and trailing comments.

    Deliberately not a shell parser. These blocks are commands to be pasted
    verbatim, and the two things a reader needs to separate at a glance are
    "this part is an explanatory comment, do not type it" and "this argument is
    one quoted unit". Guessing at builtins or variables would add colour
    without adding meaning, and would be wrong often enough to mislead.
    """
    out: list[str] = []
    plain: list[str] = []
    index = 0

    def flush() -> None:
        if plain:
            out.append(html.escape("".join(plain), quote=False))
            plain.clear()

    while index < len(line):
        char = line[index]

        if char in "'\"":
            end = line.find(char, index + 1)
            end = len(line) if end == -1 else end + 1
            flush()
            quoted = html.escape(line[index:end], quote=False)
            out.append(f'<span class="tok-str">{quoted}</span>')
            index = end
            continue

        # A comment only starts at a word boundary, so a URL fragment and a
        # printf format like '%h#x' stay untouched.
        if char == "#" and (index == 0 or line[index - 1].isspace()):
            flush()
            comment = html.escape(line[index:], quote=False)
            out.append(f'<span class="tok-comment">{comment}</span>')
            return "".join(out)

        plain.append(char)
        index += 1

    flush()
    return "".join(out)


def render_inline(text: str) -> str:
    """Render inline markup, protecting code spans from further processing."""
    spans: list[str] = []

    def stash(match: re.Match[str]) -> str:
        spans.append(html.escape(match.group(1), quote=False))
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = html.escape(text, quote=False)
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![\w*])\*(?!\s)([^*]+?)(?<!\s)\*(?![\w*])", r"<em>\1</em>", text)
    return re.sub(r"\x00(\d+)\x00", lambda m: f"<code>{spans[int(m.group(1))]}</code>", text)


def _render_cells(row: str) -> list[str]:
    return [render_inline(cell.strip()) for cell in row.strip().strip("|").split("|")]


def render_markdown(text: str) -> str:
    """Render the Markdown subset the Torio docs actually use.

    Supported: ATX headings (with optional ``{#anchor}``), paragraphs, fenced
    code, unordered and ordered lists, pipe tables, blockquotes (rendered as
    the site's callout), raw HTML blocks, and inline code/links/strong/em.
    """
    lines = text.replace("\r\n", "\n").split("\n")
    out: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        fence = FENCE.match(stripped)
        if fence:
            lang = fence.group(1)
            i += 1
            body: list[str] = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                body.append(lines[i])
                i += 1
            i += 1  # closing fence

            if lang in SHELL_LANGS:
                code = "\n".join(highlight_shell(line) for line in body)
            else:
                code = html.escape("\n".join(body), quote=False)
            attr = f' data-lang="{html.escape(lang, quote=True)}"' if lang else ""
            out.append(f'<div class="code-block"><pre{attr}><code>{code}</code></pre></div>')
            continue

        heading = HEADING.match(stripped)
        if heading:
            hashes, title, explicit = heading.groups()
            level = len(hashes)
            anchor = explicit or slug(title)
            out.append(f'<h{level} id="{anchor}">{render_inline(title)}</h{level}>')
            i += 1
            continue

        if stripped.startswith("|") and i + 1 < len(lines) and TABLE_SEP.match(lines[i + 1].strip()):
            header = _render_cells(stripped)
            i += 2
            rows: list[list[str]] = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(_render_cells(lines[i].strip()))
                i += 1
            head = "".join(f"<th>{cell}</th>" for cell in header)
            body_html = "".join(
                "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>" for row in rows
            )
            out.append(
                '<div class="table-scroll"><table><thead><tr>'
                f"{head}</tr></thead><tbody>{body_html}</tbody></table></div>"
            )
            continue

        if stripped.startswith(">"):
            quoted: list[str] = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quoted.append(lines[i].strip()[1:].lstrip())
                i += 1
            out.append(f'<div class="callout">{render_markdown(chr(10).join(quoted))}</div>')
            continue

        if UL_ITEM.match(stripped) or OL_ITEM.match(stripped):
            ordered = bool(OL_ITEM.match(stripped))
            items: list[str] = []
            while i < len(lines):
                candidate = lines[i]
                match = OL_ITEM.match(candidate.strip()) if ordered else UL_ITEM.match(candidate.strip())
                if not match:
                    # continuation line of the previous item
                    if items and candidate.startswith(("  ", "\t")) and candidate.strip():
                        items[-1] += " " + candidate.strip()
                        i += 1
                        continue
                    break
                items.append(match.group(2) if ordered else match.group(1))
                i += 1
            tag = "ol" if ordered else "ul"
            rendered = "".join(f"<li>{render_inline(item)}</li>" for item in items)
            out.append(f"<{tag}>{rendered}</{tag}>")
            continue

        if stripped.startswith("<"):
            raw: list[str] = []
            while i < len(lines) and lines[i].strip():
                raw.append(lines[i])
                i += 1
            out.append("\n".join(raw))
            continue

        para: list[str] = []
        while i < len(lines) and lines[i].strip() and not _starts_block(lines[i].strip()):
            para.append(lines[i].strip())
            i += 1
        out.append(f"<p>{render_inline(' '.join(para))}</p>")

    return "\n".join(out)


def _starts_block(stripped: str) -> bool:
    return bool(
        FENCE.match(stripped)
        or HEADING.match(stripped)
        or UL_ITEM.match(stripped)
        or OL_ITEM.match(stripped)
        or stripped.startswith(("|", ">", "<"))
    )


# --------------------------------------------------------------------------
# page assembly
# --------------------------------------------------------------------------


def load_pages(subdir: str) -> list[Page]:
    pages: list[Page] = []
    directory = CONTENT / subdir
    if not directory.is_dir():
        raise BuildError(f"no source directory at {directory.relative_to(ROOT)}")
    for path in sorted(directory.glob("*.md")):
        meta, body = parse_source(path.read_text(encoding="utf-8"), where=str(path.relative_to(ROOT)))
        for required in ("output",):
            if required not in meta:
                raise BuildError(f"{path.relative_to(ROOT)}: front matter is missing '{required}'")
        pages.append(Page(source=path, meta=meta, body=body))
    return pages


def nav_html(pages: list[Page], current: str) -> str:
    items: list[str] = []
    for page in sorted(pages, key=lambda p: int(p.meta.get("order", "99"))):
        if "nav" not in page.meta:
            continue
        href = Path(page.meta["output"]).name
        current_attr = ' aria-current="page"' if href == current else ""
        items.append(f'<li><a href="{href}"{current_attr}>{html.escape(page.meta["nav"])}</a></li>')
    return "\n            ".join(items)


def render_page(page: Page, pages: list[Page], blocks: dict[str, Block], layout: str) -> str:
    where = str(page.source.relative_to(ROOT))
    body = expand_toc(expand_includes(page.body, blocks, where=where))
    output_name = Path(page.meta["output"]).name

    scope = page.meta.get("scope_notice", "")
    scope_html = (
        f'<div class="wrap">\n        <p class="scope-notice">{render_inline(scope)}</p>\n      </div>'
        if scope
        else ""
    )
    kicker = page.meta.get("kicker", "")
    kicker_html = f'<span class="mode-kicker">{html.escape(kicker)}</span>\n        ' if kicker else ""

    rendered = layout
    replacements = {
        "banner": BANNER_HTML.format(source=where),
        "title": html.escape(page.meta.get("title", "Torio")),
        "description": html.escape(page.meta.get("description", "")),
        "page_id": Path(output_name).stem,
        "nav": nav_html(pages, output_name),
        "scope_notice": scope_html,
        "kicker": kicker_html,
        "content": render_markdown(body),
        "repo_url": REPO_URL,
    }
    for key, value in replacements.items():
        rendered = rendered.replace("{{" + key + "}}", value)

    leftover = re.search(r"\{\{([a-z_]+)\}\}", rendered)
    if leftover:
        raise BuildError(f"{where}: layout placeholder {{{{{leftover.group(1)}}}}} was never filled")
    return rendered.rstrip() + "\n"


def render_runbook(page: Page, blocks: dict[str, Block]) -> str:
    where = str(page.source.relative_to(ROOT))
    body = strip_anchor_syntax(expand_toc(expand_includes(page.body, blocks, where=where)))
    return BANNER_MD.format(source=where) + "\n\n" + body.strip("\n") + "\n"


def build() -> dict[str, str]:
    blocks = load_blocks()
    problems = check_block_portability(blocks)
    if problems:
        raise BuildError("shared blocks are not portable:\n  - " + "\n  - ".join(problems))
    site_pages = load_pages("pages")
    runbooks = load_pages("runbooks")
    layout = LAYOUT.read_text(encoding="utf-8")

    outputs: dict[str, str] = {}
    for page in site_pages:
        outputs[page.meta["output"]] = render_page(page, site_pages, blocks, layout)
    for page in runbooks:
        outputs[page.meta["output"]] = render_runbook(page, blocks)
    return outputs


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------


def diff_outputs(rendered: dict[str, str], on_disk: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for path in sorted(rendered):
        if path not in on_disk:
            problems.append(f"{path}: generated file is missing")
        elif on_disk[path] != rendered[path]:
            problems.append(f"{path}: generated file is stale")
    return problems


def read_on_disk(paths: list[str]) -> dict[str, str]:
    found: dict[str, str] = {}
    for path in paths:
        full = ROOT / path
        if full.exists():
            found[path] = full.read_text(encoding="utf-8")
    return found


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="render in memory and fail if any generated file is stale; writes nothing",
    )
    args = parser.parse_args(argv)

    try:
        rendered = build()
    except BuildError as exc:
        print(f"docs build FAILED: {exc}", file=sys.stderr)
        return 1

    if args.check:
        problems = diff_outputs(rendered, read_on_disk(list(rendered)))
        if problems:
            print("docs build check FAILED — regenerate with: python3 scripts/build_docs.py")
            for problem in problems:
                print(f"  - {problem}")
            return 1
        print(f"docs build check OK: {len(rendered)} generated files match their sources")
        return 0

    for path, text in sorted(rendered.items()):
        full = ROOT / path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(text, encoding="utf-8")
    print(f"docs build OK: wrote {len(rendered)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
